name = "Nana"
uuid = "38acdeaf-591f-464b-a574-6d5e273eff13"
authors = ["jahernando"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
